import { Person } from './types';

export const mockPeople: Person[] = [
  {
    id: '1',
    name: 'Alex Morgan',
    title: 'Design Systems Director',
    department: 'Product',
    email: 'amorgan@acme.com',
    initials: 'AM',
    manager: 'Anderson, Sam',
    managerTitle: 'Manager',
    businessUnit: 'Product',
    location: 'Santa Clara',
    mentoringStatus: 'not-available',
    coffeeChat: true,
  },
  {
    id: '2',
    name: 'Jordan Lee',
    title: 'Principal UX Designer',
    department: 'Product',
    email: 'jlee@acme.com',
    initials: 'JL',
    manager: 'Anderson, Sam',
    managerTitle: 'Manager',
    businessUnit: 'Product',
    location: 'Remote - US - CA',
    mentoringStatus: 'open',
    connectionInfo: 'You started at Acme Corp 1 month before Jordan',
    participationInfo: 'Jordan participated in: Project Usability - Heuristic Evaluation',
  },
  {
    id: '3',
    name: 'Taylor Kim',
    title: 'Senior Product Manager',
    department: 'Product',
    email: 'tkim@acme.com',
    initials: 'TK',
    manager: 'Johnson, Pat',
    managerTitle: 'VP Product',
    businessUnit: 'Product',
    location: 'San Francisco',
    mentoringStatus: 'open',
    connectionInfo: 'You worked together on 3 projects',
  },
  {
    id: '4',
    name: 'Casey Patel',
    title: 'Staff Software Engineer',
    department: 'Engineering',
    email: 'cpatel@acme.com',
    initials: 'CP',
    manager: 'Kumar, Priya',
    managerTitle: 'Engineering Manager',
    businessUnit: 'Engineering',
    location: 'Bangalore',
    mentoringStatus: 'open',
    coffeeChat: true,
  },
  {
    id: '5',
    name: 'Morgan Garcia',
    title: 'Senior UX Researcher',
    department: 'Design',
    email: 'mgarcia@acme.com',
    initials: 'MG',
    manager: 'Lee, Susan',
    managerTitle: 'Design Lead',
    businessUnit: 'Product',
    location: 'New York',
    mentoringStatus: 'open',
    participationInfo: 'Morgan participated in: User Research Sprint Q3',
  },
  {
    id: '6',
    name: 'Riley Chen',
    title: 'Engineering Manager',
    department: 'Engineering',
    email: 'rchen@acme.com',
    initials: 'RC',
    manager: 'Smith, Jamie',
    managerTitle: 'Director of Engineering',
    businessUnit: 'Engineering',
    location: 'Seattle',
    mentoringStatus: 'not-available',
  },
  {
    id: '7',
    name: 'Jamie Novak',
    title: 'Product Designer',
    department: 'Design',
    email: 'jnovak@acme.com',
    initials: 'JN',
    manager: 'Brown, Lisa',
    managerTitle: 'Design Manager',
    businessUnit: 'Product',
    location: 'Remote - EU - PL',
    mentoringStatus: 'open',
    coffeeChat: true,
  },
  {
    id: '8',
    name: 'Quinn Davis',
    title: 'Data Scientist',
    department: 'Data Science',
    email: 'qdavis@acme.com',
    initials: 'QD',
    manager: 'Davis, Robin',
    managerTitle: 'Senior Manager',
    businessUnit: 'AI/ML',
    location: 'Boston',
    mentoringStatus: 'open',
  },
];
