import { Person } from './types';

export const mockPeople: Person[] = [
  {
    id: '1',
    name: 'Yair Pike',
    title: 'Design Systems Director',
    department: 'Product',
    email: 'ypike@eightfold.ai',
    initials: 'YP',
    manager: 'Srinivasaraju, Ruta',
    managerTitle: 'Manager',
    businessUnit: 'Product',
    location: 'Santa Clara',
    mentoringStatus: 'not-available',
    coffeeChat: true,
  },
  {
    id: '2',
    name: 'David Thomas',
    title: 'Principal UX Designer',
    department: 'Product',
    email: 'dthomas@eightfold.ai',
    initials: 'DT',
    manager: 'Srinivasaraju, Ruta',
    managerTitle: 'Manager',
    businessUnit: 'Product',
    location: 'Remote - US - CA',
    mentoringStatus: 'open',
    connectionInfo: 'You started at Eightfold AI 1 month before David',
    participationInfo: 'David participated in: Project Usability - Heuristic Evaluation',
  },
  {
    id: '3',
    name: 'Sarah Chen',
    title: 'Senior Product Manager',
    department: 'Product',
    email: 'schen@eightfold.ai',
    initials: 'SC',
    manager: 'Johnson, Michael',
    managerTitle: 'VP Product',
    businessUnit: 'Product',
    location: 'San Francisco',
    mentoringStatus: 'open',
    connectionInfo: 'You worked together on 3 projects',
  },
  {
    id: '4',
    name: 'Raj Patel',
    title: 'Staff Software Engineer',
    department: 'Engineering',
    email: 'rpatel@eightfold.ai',
    initials: 'RP',
    manager: 'Kumar, Priya',
    managerTitle: 'Engineering Manager',
    businessUnit: 'Engineering',
    location: 'Bangalore',
    mentoringStatus: 'open',
    coffeeChat: true,
  },
  {
    id: '5',
    name: 'Emily Rodriguez',
    title: 'Senior UX Researcher',
    department: 'Design',
    email: 'erodriguez@eightfold.ai',
    initials: 'ER',
    manager: 'Lee, Susan',
    managerTitle: 'Design Lead',
    businessUnit: 'Product',
    location: 'New York',
    mentoringStatus: 'open',
    participationInfo: 'Emily participated in: User Research Sprint Q3',
  },
  {
    id: '6',
    name: 'Michael Zhang',
    title: 'Engineering Manager',
    department: 'Engineering',
    email: 'mzhang@eightfold.ai',
    initials: 'MZ',
    manager: 'Smith, James',
    managerTitle: 'Director of Engineering',
    businessUnit: 'Engineering',
    location: 'Seattle',
    mentoringStatus: 'not-available',
  },
  {
    id: '7',
    name: 'Anna Kowalski',
    title: 'Product Designer',
    department: 'Design',
    email: 'akowalski@eightfold.ai',
    initials: 'AK',
    manager: 'Brown, Lisa',
    managerTitle: 'Design Manager',
    businessUnit: 'Product',
    location: 'Remote - EU - PL',
    mentoringStatus: 'open',
    coffeeChat: true,
  },
  {
    id: '8',
    name: 'James Wilson',
    title: 'Data Scientist',
    department: 'Data Science',
    email: 'jwilson@eightfold.ai',
    initials: 'JW',
    manager: 'Davis, Robert',
    managerTitle: 'Senior Manager',
    businessUnit: 'AI/ML',
    location: 'Boston',
    mentoringStatus: 'open',
  },
];

